export const autofillBorrower = {
  uuidActiveLocal: '',
  listContactPersonUUID: [],
  info: [
    {
      uuidActiveLocal: '',
      declare: ['RELATED'],
      basic: {
        person_uuid: '',
        fullname: 'TRẦN TRỌNG NHÂN',
        customerType: 'I',
        birthday: 702061200000,
        placeOfBirth: '',
        gender: 'M',
        national: 'VN',
        marriageStatus: 'STABILITY',
        ownerProperty: 'LIVING_IN_PARENTS',
        under18: null,
        over18: 8,
        telephone: '',
        mobile: '0909123123',
        email: '',
        education: 'UNIVERSITY',
        ecomonic: 'D_0203',
        relationship: '',
        tax: '',
        cif: '',
      },
      other: {
        fatca: 'KHONG',
        career: 'A01120',
        income3Month: 'TNBQ_002',
        note: '',
      },
      identity: [
        {
          type: 'CIF_ID_TYPE',
          num: '123123123',
          issuedDate: 1648778259000,
          expiredDate: 1649469460000,
          placeOfIssue: '123',
          primaryFlag: true,
          uuid: '',
          uuidRemote: '393d4793-8e8e-8c13-d38c-ec6f6a1ab884',
        },
      ],
      address: {
        resident: 'R',
        location: '123',
        address: [
          {
            type: 'PERMANENT',
            apartment: '123',
            province: '70',
            district: '697',
            ward: '25444',
            primaryFlag: true,
            uuid: '3dc49ec2-0097-6fe9-efd6-3d6705d86493',
            uuidRemote: '',
          },
          {
            type: 'TEMP',
            apartment: '333',
            province: '70',
            district: '697',
            ward: '25435',
            primaryFlag: true,
            uuid: 'bc6d5bf0-6e66-f139-8a4e-c44764f191a2',
            uuidRemote: '',
          },
        ],
      },
      uuidActiveFile: '',
      document_info_list: [],
    },
  ],
};

export const autofillCopayer = () => {
  return [
    {
      uuidActiveLocal: 'c8160982-1f62-6b34-8bf8-1f2db752e5b6',
      declare: [],
      basic: {
        person_uuid: '',
        fullname: 'nguoi tra no 1',
        customerType: '',
        birthday: 1648793766000,
        placeOfBirth: '',
        gender: 'M',
        national: 'VN',
        marriageStatus: '',
        ownerProperty: '',
        under18: null,
        over18: null,
        telephone: '',
        mobile: '0909123199',
        email: '',
        education: '',
        ecomonic: '',
        relationship: 'FMT',
        tax: '',
        cif: '',
      },
      other: {
        fatca: '',
        career: '',
        income3Month: '',
        note: '',
      },
      identity: [
        {
          expiredDate: 1651299376000,
          issuedDate: 1648793775000,
          num: '123123333',
          placeOfIssue: '123',
          uuidRemote: 'LOCAL_048dcdcc-f9b5-46e4-f28a-e5c35bc27561',
          type: 'CIF_ID_TYPE',
          uuid: '',
          primaryFlag: true,
        },
      ],
      address: {
        resident: '',
        location: '',
        address: [
          {
            type: 'PERMANENT',
            apartment: '123',
            province: '74',
            district: '720',
            ward: '25792',
            primaryFlag: true,
            uuid: '665e6903-3bda-9623-f82c-98a2a3b2d44c',
            uuidRemote: '',
          },
          {
            type: 'TEMP',
            apartment: '444',
            province: '06',
            district: '066',
            ward: '02146',
            primaryFlag: true,
            uuid: '97a44ccb-1aa5-ace1-b047-74e970e5bde3',
            uuidRemote: '',
          },
        ],
      },
      uuidActiveFile: '',
      document_info_list: [],
    },
    {
      uuidActiveLocal: '57930d97-b838-a826-a7e0-27711add7e07',
      declare: [],
      basic: {
        person_uuid: '',
        fullname: 'nguoi tra no 2',
        customerType: '',
        birthday: 1648793793000,
        placeOfBirth: '',
        gender: 'M',
        national: 'VN',
        marriageStatus: '',
        ownerProperty: '',
        under18: null,
        over18: null,
        telephone: '',
        mobile: '0909123111',
        email: '',
        education: '',
        ecomonic: '',
        relationship: 'FMT',
        tax: '',
        cif: '',
      },
      other: {
        fatca: '',
        career: '',
        income3Month: '',
        note: '',
      },
      identity: [
        {
          expiredDate: 1651299404000,
          issuedDate: 1648793802000,
          num: '999000111',
          placeOfIssue: '123',
          uuidRemote: 'LOCAL_64b63a6f-704c-0ff4-0365-15359902dad0',
          type: 'CIF_ID_TYPE',
          uuid: '',
          primaryFlag: true,
        },
      ],
      address: {
        resident: '',
        location: '',
        address: [
          {
            type: 'PERMANENT',
            apartment: '33',
            province: '77',
            district: '752',
            ward: '26671',
            primaryFlag: true,
            uuid: '454c13da-4f99-32a8-2bb1-d9b7dfef326a',
            uuidRemote: '',
          },
          {
            type: 'TEMP',
            apartment: '4444',
            province: '24',
            district: '221',
            ward: '07702',
            primaryFlag: true,
            uuid: '004f2ac6-ccbe-8f06-887b-5f44bb2214f1',
            uuidRemote: '',
          },
        ],
      },
      uuidActiveFile: '',
      document_info_list: [],
    },
    {
      uuidActiveLocal: '2c4eee03-a682-2e8a-f250-c1c7f309f07c',
      declare: [],
      basic: {
        person_uuid: '',
        fullname: 'nguoi tra no 3',
        customerType: '',
        birthday: 1648793828000,
        placeOfBirth: '',
        gender: 'M',
        national: 'VN',
        marriageStatus: '',
        ownerProperty: '',
        under18: null,
        over18: null,
        telephone: '',
        mobile: '0909123963',
        email: '',
        education: '',
        ecomonic: '',
        relationship: 'FMT',
        tax: '',
        cif: '',
      },
      other: {
        fatca: '',
        career: '',
        income3Month: '',
        note: '',
      },
      identity: [
        {
          expiredDate: 1650003439000,
          issuedDate: 1648793837000,
          num: '999000111',
          placeOfIssue: '123',
          uuidRemote: 'LOCAL_fba735ce-6407-78cf-5867-cc6c80ec4fb1',
          type: 'CIF_ID_TYPE',
          uuid: '',
          primaryFlag: true,
        },
      ],
      address: {
        resident: '',
        location: '',
        address: [
          {
            type: 'PERMANENT',
            apartment: '222',
            province: '74',
            district: '720',
            ward: '25780',
            primaryFlag: true,
            uuid: '48b2e2c0-ad37-905c-1d2f-c8a79b4f5f19',
            uuidRemote: '',
          },
          {
            type: 'TEMP',
            apartment: '444',
            province: '06',
            district: '062',
            ward: '01939',
            primaryFlag: true,
            uuid: '9a277fec-2496-c74e-9294-7586af0034bc',
            uuidRemote: '',
          },
        ],
      },
      uuidActiveFile: '',
      document_info_list: [],
    },
  ];
};

export const autoFillAllLegal = {
  validate: {
    valid: false,
    field: 'birthday',
    role: 'empty',
    declare: 'BORROWER',
  },
  data: {
    BORROWER: {
      uuidActiveLocal: '',
      listContactPersonUUID: [],
      info: [
        {
          uuidActiveLocal: '',
          declare: [
            'MARRIAGE',
            'CO_BRW',
            'CO_PAYER',
            'LAW_RLT',
            'RELATED',
            'OTHER',
          ],
          basic: {
            person_uuid: '',
            fullname: 'người vay chính - FE',
            customerType: 'I',
            birthday: 896770142000,
            placeOfBirth: '',
            gender: 'F',
            national: 'VN',
            marriageStatus: 'SINGLE',
            ownerProperty: 'OWNER',
            under18: 1,
            over18: 3,
            telephone: '0288656988',
            mobile: '0909333444',
            email: 'phuonghoa@gmail.com',
            education: 'UNIVERSITY',
            ecomonic: 'P_0802',
            relationship: '',
            tax: '',
            cif: '',
          },
          other: {
            fatca: 'CO',
            career: 'A01120',
            income3Month: 'TNBQ_002',
            note: '',
          },
          identity: [
            {
              isModified: true,
              type: 'CIF_ID_TYPE',
              num: '301777999',
              issuedDate: 1370327384000,
              expiredDate: 1656570592000,
              placeOfIssue: 'Công An Bắc Giang',
              primaryFlag: true,
              uuid: '',
              uuidRemote: 'LOCAL_25f276f3-3a38-b39b-16b5-ebb9dee7bc66',
            },
          ],
          address: {
            resident: 'R',
            location: 'Bắc Giang',
            address: [
              {
                type: 'PERMANENT',
                apartment: '150 Trần Hừng Đạo',
                province: '24',
                district: '216',
                ward: '07321',
                primaryFlag: true,
                uuid: '0911bd4f-2c17-f30a-bad5-7d346d2dd79d',
                uuidRemote: '',
              },
              {
                type: 'TEMP',
                apartment: '160 Nguyễn Thái Học',
                province: '79',
                district: '760',
                ward: '26737',
                primaryFlag: true,
                uuid: '90bf4b95-c5eb-eb6f-d776-fd4083d64dbc',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
      ],
    },
    MARRIAGE: {
      uuidActiveLocal: '',
      listContactPersonUUID: [],
      info: [
        {
          uuidActiveLocal: '',
          declare: [],
          basic: {
            person_uuid: '',
            fullname: 'NGUYỄN VĂN tú',
            customerType: '',
            birthday: 488616588000,
            placeOfBirth: '',
            gender: 'M',
            national: 'VN',
            marriageStatus: '',
            ownerProperty: '',
            under18: null,
            over18: null,
            telephone: '',
            mobile: '0909333222',
            email: 'minhtu@gmail.com',
            education: '',
            ecomonic: '',
            relationship: '',
            tax: '',
            cif: '',
          },
          other: {
            fatca: '',
            career: '',
            income3Month: '',
            note: '',
          },
          identity: [
            {
              isModified: true,
              type: 'CIF_ID_TYPE',
              num: '301789789',
              issuedDate: 1654065170000,
              expiredDate: 1656484381000,
              placeOfIssue: '34',
              primaryFlag: true,
              uuid: '',
              uuidRemote: 'LOCAL_aac0a080-6a3b-b5a0-be0c-f996e001cf9f',
            },
          ],
          address: {
            resident: '',
            location: '',
            address: [
              {
                type: 'PERMANENT',
                apartment: '150 Nguyễn Thị Nghĩa',
                province: '64',
                district: '634',
                ward: '24001',
                primaryFlag: true,
                uuid: '336d0061-bb2c-f987-ed26-dc092d4bb757',
                uuidRemote: '',
              },
              {
                type: 'TEMP',
                apartment: '590/52 Nguyễn Văn Linh',
                province: '83',
                district: '833',
                ward: '28942',
                primaryFlag: true,
                uuid: '67937734-f800-a743-eec0-af3d773b0ed1',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
      ],
    },
    CO_BRW: {
      uuidActiveLocal: 'b1200915-2ace-59f9-1fd3-55da8cb47c96',
      listContactPersonUUID: [],
      info: [
        {
          uuidActiveLocal: 'c0d874e7-e7db-51a7-afe2-03bbacf35ce8',
          declare: [],
          basic: {
            person_uuid: '',
            fullname: 'Người đồng vay 1 ',
            customerType: '',
            birthday: 644740443000,
            placeOfBirth: '',
            gender: 'M',
            national: 'VN',
            marriageStatus: '',
            ownerProperty: '',
            under18: null,
            over18: null,
            telephone: '',
            mobile: '0908880444',
            email: '',
            education: '',
            ecomonic: '',
            relationship: 'FMT',
            tax: '',
            cif: '',
          },
          other: {
            fatca: '',
            career: '',
            income3Month: '',
            note: '',
          },
          identity: [
            {
              expiredDate: 1656570865000,
              issuedDate: 1654065263000,
              num: '999111001',
              placeOfIssue: 'Công An Bến Tre',
              uuidRemote: 'ae4f5d6c-3ba7-65cf-1b58-6a5f1685701c',
              type: 'CIF_ID_TYPE',
              uuid: '',
              primaryFlag: true,
            },
          ],
          address: {
            resident: '',
            location: '',
            address: [
              {
                type: 'PERMANENT',
                apartment: '595 Nguyễn Văn Cừ',
                province: '27',
                district: '264',
                ward: '09532',
                primaryFlag: true,
                uuid: '1733a6f0-c2a3-3ef2-5532-2f43c98e854e',
                uuidRemote: '',
              },
              {
                type: 'TEMP',
                apartment: '922 Hậu Giang',
                province: '96',
                district: '968',
                ward: '32119',
                primaryFlag: true,
                uuid: 'b31132da-71c5-ba3b-d3b4-e4b32c51741d',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
        {
          uuidActiveLocal: 'b1200915-2ace-59f9-1fd3-55da8cb47c96',
          declare: [],
          basic: {
            person_uuid: '',
            fullname: 'NGƯỜI ĐỒNG VAY 2',
            customerType: '',
            birthday: 991463643000,
            placeOfBirth: '',
            gender: 'M',
            national: 'VN',
            marriageStatus: '',
            ownerProperty: '',
            under18: null,
            over18: null,
            telephone: '',
            mobile: '0908444000',
            email: '',
            education: '',
            ecomonic: '',
            relationship: 'FMT',
            tax: '',
            cif: '',
          },
          other: {
            fatca: '',
            career: '',
            income3Month: '',
            note: '',
          },
          identity: [
            {
              expiredDate: 1656570938000,
              issuedDate: 1654065336000,
              num: '123000999',
              placeOfIssue: '123',
              uuidRemote: '9a42f553-efaf-36e6-17f3-ff1066798d28',
              type: 'CIF_ID_TYPE',
              uuid: '',
              primaryFlag: true,
            },
          ],
          address: {
            resident: '',
            location: '',
            address: [
              {
                type: 'PERMANENT',
                apartment: '500 Cà Mau',
                province: '96',
                district: '971',
                ward: '32194',
                primaryFlag: true,
                uuid: 'bb534a65-ba2a-8443-3216-59ccc650dccd',
                uuidRemote: '',
              },
              {
                type: 'TEMP',
                apartment: '600 Cần Thơ',
                province: '92',
                district: '919',
                ward: '31201',
                primaryFlag: true,
                uuid: 'f6823d13-c12d-8e5f-d3b0-b7635c1649d6',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
      ],
    },
    CO_PAYER: {
      uuidActiveLocal: 'ee32d5b0-0c59-b0dd-8b50-b12bcda955f9',
      listContactPersonUUID: [],
      info: [
        {
          uuidActiveLocal: 'f53a134c-ff64-fbdd-0ada-902e0739c097',
          declare: [],
          basic: {
            person_uuid: '',
            fullname: 'ĐỒNG TRẢ Nợ 1',
            customerType: '',
            birthday: 1370414192000,
            placeOfBirth: '',
            gender: 'M',
            national: 'VN',
            marriageStatus: '',
            ownerProperty: '',
            under18: null,
            over18: null,
            telephone: '',
            mobile: '0903765421',
            email: '',
            education: '',
            ecomonic: '',
            relationship: 'FMT_LAW',
            tax: '',
            cif: '',
          },
          other: {
            fatca: '',
            career: '',
            income3Month: '',
            note: '',
          },
          identity: [
            {
              expiredDate: 1656571012000,
              issuedDate: 1654065410000,
              num: '000999333',
              placeOfIssue: '22',
              uuidRemote: 'LOCAL_a292c0d3-5c02-9886-a3ae-0735f467ee8c',
              type: 'CIF_ID_TYPE',
              uuid: '',
              primaryFlag: true,
            },
          ],
          address: {
            resident: '',
            location: '',
            address: [
              {
                type: 'PERMANENT',
                apartment: '100 Trần Hưng Đạo',
                province: '83',
                district: '831',
                ward: '28822',
                primaryFlag: true,
                uuid: '75a8bf9e-f157-063c-e2d6-9ab7794aa12c',
                uuidRemote: '',
              },
              {
                type: 'TEMP',
                apartment: '200 Trần Hưng Đạo',
                province: '64',
                district: '638',
                ward: '24049',
                primaryFlag: true,
                uuid: 'ff27df1d-93f0-5d1f-3b4e-8dbb036360f4',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
        {
          uuidActiveLocal: 'ee32d5b0-0c59-b0dd-8b50-b12bcda955f9',
          declare: [],
          basic: {
            person_uuid: '',
            fullname: 'đồng trả nợ 2',
            customerType: '',
            birthday: 1149575860000,
            placeOfBirth: '',
            gender: 'M',
            national: 'VN',
            marriageStatus: '',
            ownerProperty: '',
            under18: null,
            over18: null,
            telephone: '',
            mobile: '0902111777',
            email: '',
            education: '',
            ecomonic: '',
            relationship: 'FMT',
            tax: '',
            cif: '',
          },
          other: {
            fatca: '',
            career: '',
            income3Month: '',
            note: '',
          },
          identity: [
            {
              expiredDate: 1656571080000,
              issuedDate: 1654065478000,
              num: '301540876',
              placeOfIssue: 'Công An Cần Thơ',
              uuidRemote: 'LOCAL_15d35e38-b2cc-866a-1f2b-093e152e4eb4',
              type: 'CIF_ID_TYPE',
              uuid: '',
              primaryFlag: true,
            },
          ],
          address: {
            resident: '',
            location: '',
            address: [
              {
                type: 'PERMANENT',
                apartment: '500 Trường Sơn',
                province: '96',
                district: '971',
                ward: '32197',
                primaryFlag: true,
                uuid: 'e206ca48-3e40-5e73-1a5c-342e9b9661a3',
                uuidRemote: '',
              },
              {
                type: 'TEMP',
                apartment: '600 Trường Sơn',
                province: '17',
                district: '158',
                ward: '05377',
                primaryFlag: true,
                uuid: 'b00292ea-f7e5-31f3-2f36-2b53be4ef50b',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
      ],
    },
    LAW_RLT: {
      uuidActiveLocal: '0bcec9e4-3ce4-be93-090a-d823d5adca28',
      listContactPersonUUID: [],
      info: [
        {
          uuidActiveLocal: '0bcec9e4-3ce4-be93-090a-d823d5adca28',
          declare: [],
          basic: {
            customerType: 'I',
            person_uuid: '',
            fullname: 'nguoi lien quan',
            birthday: null,
            placeOfBirth: '',
            gender: '',
            national: 'VN',
            marriageStatus: '',
            ownerProperty: '',
            under18: null,
            over18: null,
            telephone: '',
            mobile: '',
            email: '',
            education: '',
            ecomonic: '',
            relationship: 'FMT_LAW',
            tax: '',
            cif: '',
          },
          other: {
            fatca: '',
            career: '',
            income3Month: '',
            note: 'ghi chú',
          },
          identity: [
            {
              type: '',
              num: '888444333',
              issuedDate: null,
              expiredDate: null,
              placeOfIssue: '',
              primaryFlag: true,
              uuid: '3edbb813-c6a2-3cd9-4329-e3d8d81eea94',
              uuidRemote: 'LOCAL_fcbac2dd-ad6e-69ae-115e-bdaa29a58fde',
            },
          ],
          address: {
            location: '',
            resident: '',
            address: [
              {
                type: '',
                apartment: '595 Nguyễn Văn Cừ',
                province: '27',
                district: '264',
                ward: '09532',
                primaryFlag: true,
                uuid: '9db60fc7-2090-51a5-e569-50d4c7745234',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
        {
          uuidActiveLocal: '68847147-946c-c0e7-fa03-ac7604dcff7d',
          declare: [],
          basic: {
            customerType: 'I',
            person_uuid: '',
            fullname: 'nguoi lien quan 2',
            birthday: null,
            placeOfBirth: '',
            gender: '',
            national: 'VN',
            marriageStatus: '',
            ownerProperty: '',
            under18: null,
            over18: null,
            telephone: '',
            mobile: '',
            email: '',
            education: '',
            ecomonic: '',
            relationship: 'FMT',
            tax: '',
            cif: '',
          },
          other: {
            fatca: '',
            career: '',
            income3Month: '',
            note: 'Ghi chú 2',
          },
          identity: [
            {
              type: '',
              num: '888777444',
              issuedDate: null,
              expiredDate: null,
              placeOfIssue: '',
              primaryFlag: true,
              uuid: '654ffff6-1513-80bd-0165-424ab44588c7',
              uuidRemote: 'LOCAL_d48d0284-eab4-d727-2df5-936b87d2288b',
            },
          ],
          address: {
            location: '',
            resident: '',
            address: [
              {
                type: '',
                apartment: '500 Long An',
                province: '64',
                district: '626',
                ward: '23689',
                primaryFlag: true,
                uuid: '7aa13c4d-27fd-7a71-db29-52355493f564',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
      ],
    },
    RELATED: {
      uuidActiveLocal: '2234f766-abff-fbde-ad19-3143ff511434',
      listContactPersonUUID: [],
      info: [
        {
          uuidActiveLocal: '2234f766-abff-fbde-ad19-3143ff511434',
          declare: [],
          basic: {
            customerType: 'I',
            person_uuid: '',
            fullname: 'NGUOI LIEN HE 1',
            birthday: null,
            placeOfBirth: '',
            gender: '',
            national: 'VN',
            marriageStatus: '',
            ownerProperty: '',
            under18: null,
            over18: null,
            telephone: '',
            mobile: '0908111333',
            email: '',
            education: '',
            ecomonic: '',
            relationship: 'FMT',
            tax: '',
            cif: '',
          },
          other: {
            fatca: '',
            career: '',
            income3Month: '',
            note: '',
          },
          identity: [],
          address: {
            location: '',
            resident: '',
            address: [
              {
                type: '',
                apartment: '100 Trần Hưng Đạo',
                province: '83',
                district: '831',
                ward: '28822',
                primaryFlag: true,
                uuid: '6380f429-8200-2c7f-cb41-e5da4e43b3a1',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
      ],
    },
    OTHER: {
      uuidActiveLocal: '3ff40e74-3bbc-b3c2-2160-3cba52209cad',
      listContactPersonUUID: [],
      info: [
        {
          uuidActiveLocal: '3ff40e74-3bbc-b3c2-2160-3cba52209cad',
          declare: [],
          basic: {
            person_uuid: '',
            fullname: 'DOI TUONG KHAC 1',
            customerType: '',
            birthday: 739003232000,
            placeOfBirth: '',
            gender: 'M',
            national: 'VN',
            marriageStatus: '',
            ownerProperty: '',
            under18: null,
            over18: null,
            telephone: '',
            mobile: '0903555678',
            email: '',
            education: '',
            ecomonic: '',
            relationship: 'FOSTER_CHILD',
            tax: '',
            cif: '',
          },
          other: {
            fatca: '',
            career: '',
            income3Month: '',
            note: 'Ghi chú',
          },
          identity: [
            {
              isModified: true,
              type: 'CIF_ID_TYPE',
              num: '999000222',
              issuedDate: 1654065645000,
              expiredDate: 1656571247000,
              placeOfIssue: '123',
              primaryFlag: true,
              uuid: '',
              uuidRemote: '',
            },
          ],
          address: {
            resident: '',
            location: '',
            address: [
              {
                type: 'PERMANENT',
                apartment: '100 Trần Hưng Đạo',
                province: '83',
                district: '831',
                ward: '28822',
                primaryFlag: true,
                uuid: 'e4bc0a3c-b584-6d3c-ae07-3b65adb8af8d',
                uuidRemote: '',
              },
              {
                type: 'TEMP',
                apartment: '100 Trần Hưng Đạo',
                province: '83',
                district: '831',
                ward: '28822',
                primaryFlag: true,
                uuid: '73f4b4bf-d341-ae8c-47bb-946fb93dd1fc',
                uuidRemote: '',
              },
            ],
          },
          uuidActiveFile: '',
          document_info_list: [],
        },
      ],
    },
  },
  blacklist: null,
};
