
import { NormalActions } from 'features/loan/normal';

export const updateLOANApprovalStorage = NormalActions.updateLOANApprovalStorage
export const saveApprovalLOAN = NormalActions.saveApprovalLOAN
export const onChangeProgramData = NormalActions.onChangeProgramData
export const onChangeLoanMethodData = NormalActions.onChangeLoanMethodData
export const clearApprovalStorageLoan = NormalActions.clearApprovalStorageLoan




export const setLoanApprovalValidate = NormalActions.setLoanApprovalValidate


export const setBusinessActivitiesBasic = NormalActions.setBusinessActivitiesBasic
export const setBusinessActivitiesBusiness = NormalActions.setBusinessActivitiesBusiness
export const setBusinessActivitiesEvaluation = NormalActions.setBusinessActivitiesEvaluation
export const onchaneLOANNote = NormalActions.onchaneLOANNote

export const setBusinessActivitiesWareHousePrimary = NormalActions.setBusinessActivitiesWareHousePrimary
export const addNewWarehouseApproval = NormalActions.addNewWarehouseApproval
export const setPrimaryWarehouseApproval = NormalActions.setPrimaryWarehouseApproval
export const updateWarehouseApproval = NormalActions.updateWarehouseApproval
export const deleteWarehouseApproval = NormalActions.deleteWarehouseApproval







export const onChangeLoanCaptitalTurnOverEffect = NormalActions.onChangeLoanCaptitalTurnOverEffect
export const onChangeLoanCaptitalTotalCost = NormalActions.onChangeLoanCaptitalTotalCost
export const onChangeLoanCaptitalTurnOverLimit = NormalActions.onChangeLoanCaptitalTurnOverLimit
export const onChangeLoanLimitTotalCost = NormalActions.onChangeLoanLimitTotalCost
export const onChangeLoanLimitTotalCostOption3 = NormalActions.onChangeLoanLimitTotalCostOption3
export const updateStoreFullLoanApprovalProduct = NormalActions.updateStoreFullLoanApprovalProduct
export const updateStoreFullLoanApprovalNeedPlan = NormalActions.updateStoreFullLoanApprovalNeedPlan
export const updateStoreFullLoanApprovalProBus = NormalActions.updateStoreFullLoanApprovalProBus
export const updateStoreFullLoanApprovalLoanMethod = NormalActions.updateStoreFullLoanApprovalLoanMethod




