import { LOANCardActions } from "..";

export const fetchLOANCardConfigProductCategory = LOANCardActions.fetchLOANCardConfigProductCategory;
export const fetchLOANCardConfigProductCategoryDone = LOANCardActions.fetchLOANCardConfigProductCategoryDone;
export const fetchConfigProductCardPartnerCode = LOANCardActions.fetchConfigProductCardPartnerCode;
export const fetchConfigProductCardPartnerCodeDone = LOANCardActions.fetchConfigProductCardPartnerCodeDone;
export const fetchConfigProductCardPartnerProduct = LOANCardActions.fetchConfigProductPartnerProduct;
export const fetchConfigProductCardPartnerProductDone = LOANCardActions.fetchConfigProductPartnerProductDone;

export const setLOANNormalStorageProductCollateral = LOANCardActions.setCollateral;
export const setLOANNormalStorageProductException = LOANCardActions.setException;
